### ISSUE TITLE
create script for cluster visualization

### ISSUE THREAD

**Issue by jcarpio** [jcarpio/tropes2vec#43]

**Comment by jcarpio** [comment]
let's try to do with python3 following 
https://machinelearningmastery.com/develop-word-embeddings-python-gensim/

**Comment by JJ** [comment]
You don't visualize something because you need to fill a bit of space in the paper. You visualize something to check if it makes sense and to let the user also make sense of this. These clustering visualizations do not make sense. You don't explain them, besides. And they are not drawn in the best way for you or the reader to make sense.
If you don't know why you're doing something, it's best not to do it. If you know why you're doing it, try to convey that information in the best possible way to the reader.
In this case you (and the reader) has a certain idea of what kind of tropes should be clustered together. For instance, should character tropes go together? Should structural tropes go together? Should structural tropes be closer or further away from each other?
In order to do that, you need to do some additional processing; for instance, assign a color or shape depending on the type of trope (that can be downloaded from TvTropes). If that can't be done, at least zoom in a dense zone and explain the tropes that are there; at the same time, you should post a high-resolution version of the image somewhere.

**Comment by jcarpio** [comment]
Ok, I understood what you mean about the graphics and I think you're very right. The last few days I was totally focused on writing to finish the paper and I haven't read these comments so far. I take note for the following paper or if we had to do carmbios in this one. I have tried to explain in the results how the clusters are by analyzing two clusters. The conclusions are written in the work.
